[package]
name = "rust_leetcode"
version = "0.1.0"
authors = ["yangdianqing <yangdianqing@360.cn>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
array_tool = "1.0.3"