pub mod eighty;
pub mod eleven;
pub mod fifteen;
pub mod fifty;
pub mod five;
pub mod four;
pub mod fourteen;
pub mod fourty;
pub mod nine;
pub mod nineteen;
pub mod ninety;
pub mod one;
pub mod seven;
pub mod seventeen;
pub mod seventy;
pub mod sixteen;
pub mod sixty;
pub mod ten;
#[cfg(test)]
mod tests;
pub mod thirteen;
pub mod thirty;
pub mod twenty;
pub mod two;
pub mod two_hundred;
